name: r2dm
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - scipy=1.11.1
  - conda-forge::accelerate=0.22.0
  - conda-forge::black=23.7.0
  - conda-forge::datasets
  - conda-forge::einops=0.6.1
  - conda-forge::kornia=0.7.0
  - conda-forge::matplotlib=3.7.1
  - conda-forge::numba=0.57.0
  - conda-forge::pip=23.2.1
  - conda-forge::python=3.10
  - conda-forge::rich=13.5.1
  - conda-forge::tensorboard=2.14.0
  - conda-forge::tqdm=4.66.1
  - pytorch::pytorch-cuda=11.8
  - pytorch::pytorch=2.1.0
  - pytorch::torchvision=0.16.0
  - pip:
      - simple_parsing
      - ema-pytorch
      - imageio
      - imageio-ffmpeg
      - joblib
